version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bundle exec rdebug-ide --host 0.0.0.0 --port 3000 --dispatcher-port 26162 -- bin/rails server -b 0.0.0.0
    ports:
      - 3000:3000
    volumes:
      - .:/myapp
      - bundle_cache:/usr/local/bundle
    env_file:
      - ./docker/rails/rails.env
    environment:
      RAILS_ENV: development
    networks:
      - local_network
networks:
  local_network:
    driver: 'bridge'
volumes:
  bundle_cache:
    driver: local